import React from 'react'

const Tyc = (props) => {

    return(
        <div className="py-4">
            <h2 className="py-4">Términos y condiciones de uso</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at massa nisl. Ut enim nunc, maximus nec vulputate vitae, vehicula quis magna. Mauris ornare ex neque, vel efficitur tortor consectetur eu. Mauris pellentesque ante vel felis tincidunt, vitae viverra lectus facilisis. Praesent efficitur mollis ultrices. Etiam finibus ac nunc in gravida. Pellentesque sollicitudin rhoncus ex quis hendrerit. Curabitur id elementum turpis. Pellentesque sagittis justo vestibulum tellus pellentesque efficitur.</p>
            <p>Proin faucibus, dui sit amet fringilla accumsan, est ipsum lobortis libero, vitae commodo nulla nibh vitae ipsum. Quisque tincidunt sagittis lorem ac maximus. Morbi pellentesque, lectus at posuere maximus, justo nisi ultricies dolor, at suscipit lectus sapien eget risus. Proin non risus lacus. Maecenas facilisis orci at nulla finibus rutrum. Aenean iaculis molestie est id placerat. Praesent scelerisque accumsan pellentesque. Quisque ut nisl sed augue semper dignissim. Donec est arcu, suscipit a sapien a, euismod malesuada tellus. Mauris turpis massa, lacinia sed elit id, varius elementum leo. Nam sit amet eleifend ante. Nam ultricies maximus eros, vel sagittis massa gravida nec. Donec ut urna mi. Quisque gravida lectus faucibus ullamcorper consectetur.</p>
            <p>Vivamus at odio sed nunc porta hendrerit sed quis ligula. Vestibulum in mauris eleifend, sagittis ex at, viverra tortor. Nullam rutrum aliquam lectus, sed mollis velit. In quis enim sem. Ut pellentesque, justo et blandit porta, risus felis placerat velit, quis dignissim neque tortor dictum turpis. Suspendisse quis est mauris. Cras iaculis euismod dictum. Integer consequat scelerisque odio id auctor. Sed rhoncus, velit id sodales finibus, purus metus accumsan erat, id mollis ipsum tortor et tortor. Curabitur tempor semper nunc nec elementum. Nunc nec est quis ex tincidunt finibus. Pellentesque ut elementum risus, vel hendrerit lorem. Aenean pellentesque sollicitudin dapibus.</p>
            <p>Quisque vel hendrerit enim. Ut quis ipsum elit. Vestibulum congue quis lorem sit amet porta. Mauris ultrices nisl nisi, id tincidunt mi pellentesque at. Curabitur quis sodales magna, quis vulputate ipsum. Aliquam pellentesque, sem a convallis luctus, nunc risus vestibulum erat, ut tempor risus lacus eget odio. Nulla facilisi. Quisque feugiat nibh ligula, eget venenatis velit cursus id. Cras id neque at ipsum ultrices maximus at eget libero. Suspendisse lacus leo, rutrum pretium magna vel, ornare sodales tortor. Curabitur sodales justo at augue vehicula, at lacinia augue efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Donec nec eros magna. Vestibulum et metus viverra est congue sagittis tempor sed magna.</p>
            <p>Fusce eu metus ipsum. Integer dictum, nisl sit amet pellentesque vulputate, lacus sem convallis enim, vitae condimentum velit mi sit amet tellus. Vivamus sodales justo ac porttitor maximus. Cras molestie, turpis nec viverra placerat, lectus urna vestibulum nisl, at interdum diam nibh sit amet arcu. Donec dolor turpis, auctor vel purus et, bibendum pellentesque diam. Sed in sem tristique, pretium mi sit amet, venenatis leo. Integer nisl ligula, semper sit amet leo a, dictum sagittis urna. Quisque fringilla turpis ut justo convallis placerat. In euismod vulputate ex, ut suscipit ante hendrerit non. Duis nibh neque, dictum id ante et, maximus fringilla velit. Donec non iaculis massa, ac luctus arcu. Vivamus id velit vulputate, elementum nisl nec, aliquam nibh.</p>
            <p>Proin convallis nisl eget eros finibus, sit amet consequat augue vestibulum. Morbi dictum justo ut tempor dictum. Duis nec sodales libero. Nunc venenatis est in semper porttitor. Donec a condimentum tellus. Vivamus sed faucibus nibh. Morbi ex elit, euismod sed urna ac, laoreet scelerisque nibh. Nullam volutpat tempor dapibus. Vestibulum posuere iaculis leo. Maecenas in posuere lorem. Nulla consequat elementum vulputate. Etiam dolor nunc, commodo eget iaculis vitae, lacinia non sem.</p>
            <p>Suspendisse faucibus erat magna, sed tincidunt est pharetra sit amet. Fusce placerat urna quis rutrum molestie. Morbi facilisis egestas vehicula. Vivamus commodo neque id nisi pharetra pellentesque pretium at sapien. Curabitur in mollis lectus. Vestibulum ut velit finibus, viverra enim eu, aliquet augue. Sed imperdiet hendrerit condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec volutpat lacinia tincidunt. Donec tincidunt, leo in porta euismod, libero eros venenatis quam, ullamcorper sagittis lorem erat aliquet lacus. Nullam id lobortis leo, a venenatis ipsum.</p>
            <p>Pellentesque dignissim turpis elit, finibus pulvinar sem mollis vel. Donec eget semper lorem. Integer rutrum consectetur ante vel luctus. Curabitur tincidunt risus neque, sit amet molestie leo sodales non. Proin varius, urna quis interdum placerat, nibh diam gravida felis, ut condimentum ante ex quis felis. Mauris at finibus massa. Etiam eu quam convallis nisi dapibus posuere id sit amet leo. Ut varius massa libero, id ullamcorper nibh eleifend id.</p>
            <p>In rhoncus nisl at blandit tristique. Praesent pellentesque libero eget sapien placerat, id egestas purus vehicula. Vestibulum massa lorem, cursus vel quam vitae, hendrerit convallis risus. Nam tincidunt mi vel enim imperdiet, quis sollicitudin purus vestibulum. Proin convallis suscipit congue. Mauris finibus vehicula eros eu semper. Nunc at egestas nisi, viverra molestie neque. Fusce efficitur venenatis efficitur.</p>
            <p>Nulla lacinia nec ligula ac tincidunt. Integer imperdiet non leo a fringilla. Pellentesque suscipit efficitur euismod. Sed dignissim libero eu suscipit finibus. Nullam aliquet, nisi quis fringilla hendrerit, dolor augue pretium ante, a venenatis lorem magna eget orci. Nunc id urna id sapien efficitur faucibus sit amet eu erat. Pellentesque ligula velit, viverra nec neque nec, consectetur finibus purus. Sed lacinia urna sit amet libero venenatis hendrerit. Duis fermentum blandit velit, at maximus lorem sodales vitae. Nam commodo nisi ut dui lobortis, vel rhoncus felis sollicitudin.</p>
            <p>Vestibulum finibus ipsum non libero aliquet dictum. Nunc tristique lobortis dolor, vitae imperdiet nibh rutrum eu. Nam condimentum consectetur tortor, dictum varius lacus pulvinar at. Phasellus viverra quam in augue accumsan porta. Vivamus nec eleifend elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam accumsan erat rhoncus magna aliquet, et pulvinar dolor bibendum. In sit amet sodales orci. Praesent quis diam sit amet velit bibendum pellentesque. Etiam porttitor bibendum justo ut pellentesque. Donec eleifend mi a tortor tincidunt, a venenatis est ornare. Vestibulum sit amet metus sit amet nibh fermentum porta. Curabitur ultricies cursus lectus sed ullamcorper.</p>
            <p>Mauris gravida tellus sapien, eget blandit urna vestibulum vitae. Quisque congue tellus at eleifend maximus. Aliquam placerat quam sapien, at auctor arcu vulputate ut. In faucibus ligula urna, ac tincidunt elit auctor sed. Maecenas bibendum mollis tellus, a ullamcorper ipsum eleifend non. Nam suscipit diam eros, in convallis nisl ornare et. Nullam aliquam mollis metus, sed semper lectus fermentum porttitor. Duis et tortor ut velit finibus semper. Donec sed convallis arcu, nec lacinia ante. Sed eleifend nunc et gravida maximus. Vivamus sit amet mattis lorem, quis pretium risus. Sed nunc odio, ullamcorper sed mattis et, porttitor at nibh. Donec fermentum fermentum felis, et commodo est lobortis sed.</p>
            <p>Duis magna nisl, malesuada nec risus sed, rutrum eleifend arcu. Suspendisse et orci accumsan, tincidunt justo ut, dapibus diam. Nunc maximus aliquam vulputate. Donec magna est, iaculis eget tincidunt id, feugiat ut massa. Nunc id fermentum orci. Quisque ac sagittis velit. Phasellus convallis mi nec neque luctus, at maximus augue sodales. Cras scelerisque mi mollis hendrerit porta. Suspendisse id leo vel augue maximus hendrerit ac vitae urna. Ut maximus aliquam justo sit amet elementum. Integer congue imperdiet libero, sed luctus justo tincidunt quis. Donec varius commodo lorem, in ultricies est. Praesent sagittis turpis orci, ut posuere odio pulvinar non. Fusce vel quam vel ex bibendum dapibus.</p>
            <p>Fusce tempus, orci et tempus tincidunt, neque lacus porta mi, nec accumsan risus justo id est. Etiam enim mi, iaculis id lacinia nec, faucibus sit amet eros. Vivamus tempor, lorem ac sollicitudin bibendum, lacus justo pulvinar est, ac pretium ante felis vel ligula. Aliquam id laoreet nisl, at auctor turpis. Sed convallis arcu commodo, tincidunt nibh ut, rutrum ante. Phasellus ac luctus neque. Ut tempor libero quam, in tristique mauris tempor non. Donec fringilla, turpis sit amet porttitor tempus, nisl mauris ultrices risus, vel aliquet erat enim eget ligula. Fusce ac dapibus lectus. Sed at nisi massa. Curabitur vulputate mauris eu lorem mattis malesuada. Aenean non sollicitudin tellus, ut facilisis augue.</p>
            <p>Quisque condimentum nisl at augue commodo, quis sollicitudin augue porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae tincidunt nisi. Donec velit quam, malesuada at metus ac, tincidunt molestie nunc. Aliquam sollicitudin a augue ut condimentum. Phasellus auctor eu tortor id facilisis. Vestibulum tempor ipsum at tortor hendrerit dictum. Quisque tristique a justo vitae tincidunt. Cras posuere neque et neque venenatis vulputate. Nulla dictum viverra lorem, et tincidunt ipsum dictum quis. Quisque consequat dui nec leo malesuada scelerisque.</p>
        </div>
    )
}

export default Tyc